# Generated by Django 3.2.8 on 2021-10-27 03:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=1024)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('apellido', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('historia_clinica', models.CharField(max_length=9216, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocialPersona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_afiliado', models.CharField(max_length=1024)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.obrasocial')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obra_social', to='personas.persona')),
            ],
        ),
    ]
