# Generated by Django 3.2.7 on 2021-10-20 00:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('apellido', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('historia_clinica', models.CharField(max_length=9216, null=True)),
            ],
        ),
    ]
