# Generated by Django 3.2.7 on 2021-10-20 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=1024)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
    ]
