# Generated by Django 3.2.8 on 2021-10-20 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_obrasocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocialPersona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_afiliado', models.CharField(max_length=1024)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.obrasocial')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obra_social', to='personas.persona')),
            ],
        ),
    ]
