# Generated by Django 3.2.7 on 2021-10-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='historia_clinica',
            field=models.CharField(max_length=9216, null=True),
        ),
    ]
