# Generated by Django 3.2.7 on 2021-09-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identification',
            name='id_type',
        ),
        migrations.AddField(
            model_name='identification',
            name='type',
            field=models.CharField(choices=[('DNI', 'Dni'), ('PASAPORTE', 'Passport'), ('LC', 'Lc')], default='DNI', max_length=256),
        ),
        migrations.DeleteModel(
            name='IdentificationType',
        ),
    ]
