version: "3.5"
services:
  repec:
    build:
      context: .
    #image: httpd:2.4
    container_name: apache-laboratorio
    restart: always
    expose:
      - 80
    volumes:
      - ./dst:/usr/local/apache2/htdocs/
    network_mode: "host"