version: "3.5"
services:
  node:
    build:
      context: .
    stdin_open: true
    tty: true
    restart: "no"
    expose: 
      - 8080
    volumes:
      - ./:/src
    network_mode: "host"
    entrypoint: "/bin/bash"