FROM node:lts-buster

# RUN apt-get update && apt-get install -y curl

# RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
# RUN apt-get update && apt-get install -y \
#   nodejs \
#   && apt-get clean \
#   && rm -rf /var/lib/apt/lists/*  


ENV TZ=America/Argentina/Buenos_Aires
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN mkdir /src && chown node:node /src

RUN npm update -g
  # && npm install -g vue@2
  # && npm install -g @vue/cli

USER node
# configuro para que no tire error en las instalaciones globales de los paquetes.
# y manejar el usuario node
RUN mkdir /home/node/.npm-global \
  && npm config set prefix /home/node/.npm-global 

ENV PATH=/home/node/.npm-global/bin::/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN npm install -g vue@2 @vue/cli

WORKDIR /src

# COPY laboratorio /src

# ENTRYPOINT ["/entrypoint.sh"]
# CMD ["node"]