# Generated by Django 3.2.8 on 2021-10-27 00:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeEstudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1024)),
                ('consentimiento', models.CharField(max_length=9216, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateField(default=datetime.date.today)),
                ('presupuesto', models.FloatField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='estudios.diagnostico')),
                ('medico_derivante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios_derivados', to='personas.persona')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='personas.persona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudios.tiposdeestudio')),
            ],
        ),
    ]
