# Generated by Django 3.2.8 on 2021-10-27 03:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEstudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1024)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='TiposDeEstudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1024)),
                ('consentimiento', models.CharField(max_length=9216, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EsperandoPresupuesto',
            fields=[
                ('estadoestudio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estudios.estadoestudio')),
                ('presupuesto', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('estudios.estadoestudio',),
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateField(default=datetime.date.today)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='estudios.diagnostico')),
                ('medico_derivante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios_derivados', to='personas.persona')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='personas.persona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudios.tiposdeestudio')),
            ],
        ),
        migrations.AddField(
            model_name='estadoestudio',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='estudios.estudio'),
        ),
        migrations.AddField(
            model_name='estadoestudio',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_estudios.estadoestudio_set+', to='contenttypes.contenttype'),
        ),
    ]
