# Generated by Django 3.2.8 on 2021-10-27 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsperandoFactura',
            fields=[
                ('estadoestudio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estudios.estadoestudio')),
                ('fecha_factura', models.DateField(auto_now=True)),
                ('numero', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('obra_social', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.obrasocial')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('estudios.estadoestudio',),
        ),
    ]
