# Generated by Django 3.2.8 on 2021-10-27 02:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEstudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='presupuesto',
        ),
        migrations.CreateModel(
            name='PresupuestoEstudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('presupuesto', models.FloatField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudios.estadoestudio')),
            ],
        ),
        migrations.AddField(
            model_name='estadoestudio',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='estudios.estudio'),
        ),
    ]
