# Generated by Django 3.2.8 on 2021-10-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0002_auto_20211026_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoestudio',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
