# Generated by Django 3.2.8 on 2021-10-21 00:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_obrasocialpersona'),
        ('estudios', '0002_tipoestudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateField()),
                ('historia_clinica', models.CharField(max_length=9216)),
                ('presupuesto', models.FloatField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='estudios.diagnostico')),
                ('medico_derivante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios_derivados', to='personas.persona')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='personas.persona')),
            ],
        ),
    ]
