# Generated by Django 3.2.8 on 2021-10-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0002_esperandofactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoestudio',
            name='nombre',
        ),
    ]
