# Generated by Django 3.2.8 on 2021-10-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0004_rename_consentimineto_tipoestudio_consentimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoestudio',
            name='consentimiento',
            field=models.CharField(max_length=9216, null=True),
        ),
    ]
