# Generated by Django 3.2.8 on 2021-10-21 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0005_alter_tipoestudio_consentimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='historia_clinica',
        ),
    ]
