# Generated by Django 3.2.8 on 2021-10-21 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0006_remove_estudio_historia_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='fecha_alta',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
